### ISSUE TITLE
[Suggestions] Tiny Smart Battery

### ISSUE THREAD

**Issue by kaedys** [MrMinemeet/ONI-Mods#1]
Can we get a tiny version of the Smart Battery added to the Tiny Battery mod? Would be amazing for controlling generators if we could just place the control battery inline, rather than needing a 2x2 space.

**Comment by MrMinemeet** [comment]
sorry for responding more than 4 years later. Didn't play the game for quite some time and also haven't realized that someone actually created an issue.

I'm not sure if tiny smart batteries ever made it onto steam. At least some code on this repo suggests that it was added.
I'm currently trying to get the mod working again as for #2 . In that update to steam, the tiny Smart batteries will be added then, if it wasn't before.

**Comment by MrMinemeet** [comment]
Hi,

I published a preview of #2 on steam which includes the Tiny Smart Battery.
Some small but known scaling issues included 😉 
https://github.com/MrMinemeet/ONI-Mods/issues/2#issuecomment-2365226734
